server:
  error:
    include-stacktrace: never


spring:
  datasource:
    url: jdbc:h2:mem:wall_app_db
    username: admin
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect