spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallapp
    username: wallappadmin
    password: wallappadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092

wall-app:
  security:
    key: d8a16303a09480714e2201a2a97a237f47ee18c78f6bc41e404daf182d0f8980
    expiration:
      time: 1
      unit: DAY
    frontend-origins:
      - http://localhost:3000
  aws:
    secretKey: wallappadmin
    accessKey: wallappadmin
    s3:
      service-endpoint: http://localhost:9000
